pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    docker.build('user/repo:latest')
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'kubectl apply -f kubernetes/deployment.yaml'
                    sh 'kubectl apply -f kubernetes/service.yaml'
                    sh 'kubectl apply -f kubernetes/ingress.yaml'
                }
            }
        }
    }
}
